// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package handler

// RecordSnippet Snippet of the record resource
type RecordSnippet struct {
	Excerpt *string   `json:"excerpt,omitempty"`
	Id      *string   `json:"id,omitempty"`
	Tags    *[]string `json:"tags,omitempty"`
}

// GetRecordsParams defines parameters for GetRecords.
type GetRecordsParams struct {
	Tag *[]string `form:"tag,omitempty" json:"tag,omitempty"`
}

// PostRecordsJSONBody defines parameters for PostRecords.
type PostRecordsJSONBody struct {
	Content *string   `json:"content,omitempty"`
	Tags    *[]string `json:"tags,omitempty"`
}

// PostRecordsJSONRequestBody defines body for PostRecords for application/json ContentType.
type PostRecordsJSONRequestBody PostRecordsJSONBody
