// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package storage

import (
	"github.com/google/uuid"
)

type Record struct {
	ID      uuid.UUID
	Content string
}

type RecordTag struct {
	RecordID uuid.UUID
	TagID    string
}

type Tag struct {
	ID string
}
