// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package storage

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssociateNoteToTag(ctx context.Context, db DBTX, arg AssociateNoteToTagParams) error
	CreateRecord(ctx context.Context, db DBTX, arg CreateRecordParams) (uuid.UUID, error)
	GetRecordsByTag(ctx context.Context, db DBTX, tagID string) ([]GetRecordsByTagRow, error)
	GetTag(ctx context.Context, db DBTX, id string) (string, error)
	UpsertTag(ctx context.Context, db DBTX, id string) error
}

var _ Querier = (*Queries)(nil)
