// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: tag.sql

package storage

import (
	"context"
)

const getTag = `-- name: GetTag :one
SELECT id FROM tag
WHERE id = $1
`

func (q *Queries) GetTag(ctx context.Context, db DBTX, id string) (string, error) {
	row := db.QueryRowContext(ctx, getTag, id)
	err := row.Scan(&id)
	return id, err
}

const upsertTag = `-- name: UpsertTag :exec
insert into tag (id) values ($1)
on conflict (id) do nothing
`

func (q *Queries) UpsertTag(ctx context.Context, db DBTX, id string) error {
	_, err := db.ExecContext(ctx, upsertTag, id)
	return err
}
