run:
  timeout: 5m
  skip-dirs:
    - codegen
  skip-dirs-use-default: false
output:
  sort-results: true
linters:
  fast: true  
  enable:
  - bodyclose
  - contextcheck
  - decorder
  - dupl
  - durationcheck
  - errname
  - errorlint
  - exhaustive
  - exportloopref
  - gci
  - gocognit
  - goconst
  - gofmt
  - goimports
  - gomnd
  - importas
  - interfacebloat
  - maintidx
  - misspell
  - nilerr
  - nilnil
  - prealloc
  - tenv
  - unconvert
  - unparam
  - usestdlibvars
  - wrapcheck
issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - bodyclose
        - contextcheck
        - errname
        - errorlint
        - exhaustive
        - gocognit
        - goconst
        - gomnd
        - interfacebloat
        - maintidx
        - nilerr
        - nilnil
        - prealloc
        - unconvert
        - unparam
        - usestdlibvars
        - wrapcheck
linters-settings:
  wrapcheck:
    ignoreSigs:
      - errors.RootCause(
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(